# Auto-label new issues with your default labels!
# Set or add labels in the 'labels' list.

name: Auto Label New Issues

on:
  issues:
    types: [opened]

permissions:
  issues: write
  contents: read

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Add labels
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Add or tweak your labels here
            const labels = ["triage", "copilot"]; // <-- TUNE ME!
            try {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels
              });
              console.log(`✅ Added labels [${labels.join(", ")}] to issue #${context.issue.number}`);
            } catch (error) {
              console.log(`⚠️ Failed to add labels to issue #${context.issue.number}`);
              console.log(`Error: ${error.message}`);
              console.log("Note: This may happen if labels don't exist or there are permission issues.");
              console.log("The issue will continue to be processed normally.");
              // Don't throw the error - let the workflow continue
            }