#!/bin/bash
# Verification script for Podman/Docker compose setup.
# This script checks that the containerized opsechat is running correctly.

set -euo pipefail

SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(cd "$(dirname "$SCRIPT_PATH")" && pwd)"
source "$SCRIPT_DIR/compose-common.sh"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

if ! detect_compose; then
    echo -e "${RED}[!] Error: Neither podman-compose nor docker-compose found.${NC}"
    exit 1
fi

echo "========================================"
echo "Opsechat Container Verification"
echo "========================================"
echo ""

# Check if containers are running
echo -e "${YELLOW}[*]${NC} Checking container status..."
if is_service_present_in_ps "opsechat-tor"; then
    echo -e "${GREEN}[✓]${NC} Tor container is running"
else
    echo -e "${RED}[✗]${NC} Tor container is not running"
    echo "    Run: ./compose-up.sh"
    exit 1
fi

if is_service_present_in_ps "opsechat-app"; then
    echo -e "${GREEN}[✓]${NC} Opsechat container is running"
else
    echo -e "${RED}[✗]${NC} Opsechat container is not running"
    echo "    Run: ./compose-up.sh"
    exit 1
fi

# Check Tor health
echo ""
echo -e "${YELLOW}[*]${NC} Checking Tor service health..."
if run_compose exec -T tor nc -z localhost 9051 2>/dev/null; then
    echo -e "${GREEN}[✓]${NC} Tor control port is accessible (9051)"
else
    echo -e "${RED}[✗]${NC} Tor control port is not accessible"
fi

if run_compose exec -T tor nc -z localhost 9050 2>/dev/null; then
    echo -e "${GREEN}[✓]${NC} Tor SOCKS port is accessible (9050)"
else
    echo -e "${RED}[✗]${NC} Tor SOCKS port is not accessible"
fi

# Check if opsechat generated an onion address
echo ""
echo -e "${YELLOW}[*]${NC} Checking for hidden service address..."
# Tor v3 onion addresses are typically 56 characters followed by .onion
# The path portion is generated by opsechat and may vary in length
# This pattern matches common formats but may need adjustment for edge cases
LOGS="$(run_compose logs opsechat 2>/dev/null | grep -Eo "[a-z2-7]{16,56}\.onion/[a-zA-Z0-9_-]{8,}" | head -1 || true)"

if [ ! -z "$LOGS" ]; then
    echo -e "${GREEN}[✓]${NC} Hidden service is running"
    echo ""
    echo "========================================"
    echo -e "${GREEN}Your opsechat service is available at:${NC}"
    echo -e "${GREEN}$LOGS${NC}"
    echo "========================================"
    echo ""
    echo "Open this URL in Tor Browser to access your chat!"
else
    echo -e "${YELLOW}[⚠]${NC} Hidden service address not found in logs yet"
    echo "    This may take a minute or two..."
    echo "    Run: $COMPOSE_CMD -f $COMPOSE_FILE logs opsechat"
fi

# Check network connectivity
echo ""
echo -e "${YELLOW}[*]${NC} Checking container network..."
if run_compose exec -T opsechat ping -c 1 tor &>/dev/null; then
    echo -e "${GREEN}[✓]${NC} Opsechat can reach Tor container"
else
    echo -e "${YELLOW}[⚠]${NC} Network connectivity check failed (may not be critical)"
fi

# Resource usage
echo ""
echo -e "${YELLOW}[*]${NC} Container resource usage:"
run_compose ps

echo ""
echo "========================================"
echo -e "${GREEN}Verification complete!${NC}"
echo "========================================"
echo ""
echo "Useful commands:"
echo "  View logs:          $COMPOSE_CMD -f $COMPOSE_FILE logs -f"
echo "  Restart services:   ./compose-down.sh && ./compose-up.sh"
echo "  Stop services:      ./compose-down.sh"
echo ""
